# Generated by Django 6.0.5 on 2026-05-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_quantity', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='products.cpu')),
                ('keyboard_mouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='products.keyboardmouse')),
                ('monoblock_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='products.monoblockbase')),
                ('primary_storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_quotes', to='products.storage')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='products.ram')),
                ('secondary_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_quotes', to='products.storage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
