# Generated by Django 6.0.5 on 2026-05-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildquote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saved Calculation', 'verbose_name_plural': 'Saved Calculations'},
        ),
    ]
