# Generated by Django 6.0.5 on 2026-05-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_buildquote_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildquote',
            name='primary_storage',
        ),
        migrations.RemoveField(
            model_name='buildquote',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='buildquote',
            name='ram_quantity',
        ),
        migrations.RemoveField(
            model_name='buildquote',
            name='secondary_storage',
        ),
        migrations.AddField(
            model_name='buildquote',
            name='ram_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='buildquote',
            name='storage_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
