# Generated by Django 5.2.14 on 2026-05-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_buildquote_primary_storage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Dollar kursi (so'm)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kalkulyator sozlamalari',
                'verbose_name_plural': 'Kalkulyator sozlamalari',
            },
        ),
    ]
