# Generated by Django 5.2.14 on 2026-05-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_calculatorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorsettings',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="10% ustamadan ayiriladi. 0 = chegirma yo'q, 1–6 = chegirma foizi.", max_digits=4, verbose_name='Chegirma (%)'),
        ),
    ]
