# Generated by Django 5.2.14 on 2026-05-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_calculatorsettings_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='discount_percent',
        ),
    ]
