# Generated by Django 5.2.14 on 2026-05-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_remove_calculatorsettings_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildquote',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Chegirma (%)'),
        ),
        migrations.AddField(
            model_name='buildquote',
            name='markup_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ustama summasi (USD)'),
        ),
        migrations.AddField(
            model_name='buildquote',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4, verbose_name='Ustama (%)'),
        ),
        migrations.AddField(
            model_name='buildquote',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sof narx (USD)'),
        ),
        migrations.AddField(
            model_name='buildquote',
            name='total_price_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Jami (so'm)"),
        ),
        migrations.AddField(
            model_name='buildquote',
            name='usd_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Dollar kursi (so'm)"),
        ),
        migrations.AlterField(
            model_name='buildquote',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami (USD)'),
        ),
    ]
