# Generated by Django 5.2.14 on 2026-05-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_buildquote_discount_percent_buildquote_markup_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildquote',
            name='order_number',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='Zakaz raqami'),
        ),
    ]
