# Generated by Django 5.2.14 on 2026-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_buildquote_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorsettings',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Ustama (%)'),
        ),
    ]
