# Generated by Django 5.2.14 on 2026-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_add_markup_percent_to_calculatorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorsettings',
            name='max_discount_percent',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Maksimal chegirma (%)'),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='min_markup_percent',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Minimal ustama (%)'),
        ),
    ]
