# Generated by Django 5.2.14 on 2026-06-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_add_discount_range_to_calculatorsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='min_markup_percent',
        ),
    ]
