# Generated by Django 5.2.14 on 2026-06-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_remove_min_markup_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatorsettings',
            options={'verbose_name': 'Calculator Settings', 'verbose_name_plural': 'Calculator Settings'},
        ),
    ]
