# Generated by Django 5.2.14 on 2026-06-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_alter_calculatorsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildquote',
            options={'ordering': ['-created_at'], 'verbose_name': 'AIO Calculation', 'verbose_name_plural': 'AIO Calculations'},
        ),
        migrations.AlterModelOptions(
            name='calculatorsettings',
            options={'verbose_name': 'AIO Calculator Settings', 'verbose_name_plural': 'AIO Calculator Settings'},
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='branded_aio_markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Branded AIO ustama (%)'),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='branded_pc_markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Branded PC ustama (%)'),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='laptops_markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Laptops ustama (%)'),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='monitors_markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Monitors ustama (%)'),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='printers_markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Printers ustama (%)'),
        ),
        migrations.AlterField(
            model_name='calculatorsettings',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='AIO ustama (%)'),
        ),
    ]
