# Generated by Django 5.2.14 on 2026-07-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_add_per_section_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='branded_aio_markup_percent',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='branded_pc_markup_percent',
        ),
        migrations.RemoveField(
            model_name='calculatorsettings',
            name='laptops_markup_percent',
        ),
    ]
