# Generated by Django 4.2.30 on 2026-06-28 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0013_add_per_section_markup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='Buyurtma raqami')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Mijoz ismi')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Telefon raqami')),
                ('region', models.CharField(max_length=80, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=80, verbose_name='Tuman')),
                ('city', models.CharField(max_length=80, verbose_name='Shahar')),
                ('landmark', models.CharField(blank=True, max_length=200, verbose_name="Mo'ljal")),
                ('delivery_type', models.CharField(choices=[('BTS', 'BTS'), ('UZPOST', 'UZPOST'), ('PICKUP', 'Olib ketadi'), ('DELIVERY', 'Olib borish kerak')], max_length=20, verbose_name='Yetkazish turi')),
                ('payment_type', models.CharField(choices=[('CARD', 'Karta'), ('CASH', 'Naqt'), ('TRANSFER', "Pul ko'chirish"), ('CASH_CARD', 'Naqt + Karta')], max_length=20, verbose_name="To'lov turi")),
                ('payment_status', models.CharField(choices=[('PAID', "To'langan"), ('ON_DELIVERY', 'Yetkazilganda'), ('PARTIAL', 'Qisman')], default='ON_DELIVERY', max_length=20, verbose_name="To'lov holati")),
                ('production_status', models.CharField(choices=[('QUEUED', 'Navbatda'), ('IN_PROGRESS', "Yig'ilmoqda"), ('READY', 'Tayyor'), ('SHIPPING', 'Yetkazilmoqda'), ('DELIVERED', 'Yetkazib berildi'), ('CANCELLED', 'Bekor qilindi')], default='QUEUED', max_length=20, verbose_name='Ishlab chiqarish holati')),
                ('total_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami (USD)')),
                ('total_price_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name="Jami (so'm)")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazib berilgan vaqt')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_label', models.CharField(max_length=255, verbose_name='Konfiguratsiya')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('unit_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dona narxi (USD)')),
                ('build_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='calculator.buildquote', verbose_name='Kalkulyator konfiguratsiyasi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
    ]
