# Generated by Django 5.2.14 on 2026-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yetkazib berish sanasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Yetkazib berish vaqti'),
        ),
        migrations.AddField(
            model_name='order',
            name='partial_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name="Qisman to'langan summa"),
        ),
        migrations.AlterField(
            model_name='order',
            name='production_status',
            field=models.CharField(choices=[('QUEUED', 'Navbatda'), ('IN_PROGRESS', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('DELIVERED', 'Yetkazildi'), ('CANCELLED', 'Bekor qilindi')], default='QUEUED', max_length=20, verbose_name='Ishlab chiqarish holati'),
        ),
    ]
