# Generated by Django 5.2.14 on 2026-07-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_date_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name="Dona narxi (so'm)"),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('POST', 'POCHTA (BTS, UZPOST, ...)'), ('PICKUP', 'OLIB KETADI'), ('DELIVERY', 'OLIB BORISH KERAK')], max_length=20, verbose_name='Yetkazish turi'),
        ),
    ]
