# Generated by Django 5.2.14 on 2026-07-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_unit_price_uzs_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('DELIVERY', 'Olib borish kerak'), ('POST', 'Pochta (BTS, UzPost, YandexGo...)'), ('PICKUP', 'Olib ketadi')], max_length=20, verbose_name='Yetkazish turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', "To'lanmagan"), ('ON_DELIVERY', "Yetkazilganda to'lanadi"), ('ON_PICKUP', "Olib ketishda to'lanadi"), ('PARTIAL', "Qisman to'langan"), ('PAID', "To'langan")], default='UNPAID', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', "Naqd to'lov"), ('CARD', "Kartadan to'lov"), ('TRANSFER', 'Bank orqali'), ('CASH_CARD', "Aralash to'lov")], max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='order',
            name='production_status',
            field=models.CharField(choices=[('AGREED', 'Kelishuvda'), ('QUEUED', 'Navbatda'), ('IN_PROGRESS', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('SHIPPING', "Yo'lda"), ('DELIVERED', 'Yetkazildi'), ('ON_HOLD', "To'xtatildi"), ('CANCELLED', 'Bekor qilindi')], default='AGREED', max_length=20, verbose_name='Ishlab chiqarish holati'),
        ),
    ]
