# Generated by Django 5.2.14 on 2026-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_type_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='production_status',
            field=models.CharField(choices=[('AGREED', 'Kelishuvda'), ('QUEUED', 'Navbatda'), ('IN_PROGRESS', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('SHIPPING', "Yo'lda"), ('DELIVERED', 'Yetkazildi'), ('COMPLETED', 'Yakunlandi'), ('ON_HOLD', "To'xtatildi"), ('CANCELLED', 'Bekor qilindi')], default='AGREED', max_length=20, verbose_name='Ishlab chiqarish holati'),
        ),
    ]
