# Generated by Django 6.0.5 on 2026-05-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Keyboard and mouse',
                'verbose_name_plural': 'Keyboard and mouse',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('ram_type', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=10)),
                ('capacity_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAM',
                'ordering': ['ram_type', 'capacity_gb', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD')], max_length=10)),
                ('interface', models.CharField(choices=[('sata', 'SATA'), ('nvme', 'NVMe')], max_length=10)),
                ('capacity_gb', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['kind', 'interface', 'capacity_gb', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonoblockBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('motherboard_type', models.CharField(max_length=40)),
                ('ram_type', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=10)),
                ('ram_slots', models.PositiveSmallIntegerField(default=2)),
                ('sata_ports', models.PositiveSmallIntegerField(default=1)),
                ('supports_nvme', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Monoblock base',
                'verbose_name_plural': 'Monoblock bases',
                'ordering': ['motherboard_type', 'ram_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'motherboard_type', 'ram_type'), name='unique_monoblock_base')],
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('compatible_bases', models.ManyToManyField(related_name='cpus', to='products.monoblockbase')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPUs',
                'ordering': ['name'],
            },
        ),
    ]
