# Generated by Django 5.2.14 on 2026-05-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyboardmouse',
            options={'ordering': ['name'], 'verbose_name': 'Keyboard and Mouse', 'verbose_name_plural': 'Keyboard and Mouse'},
        ),
        migrations.AlterModelOptions(
            name='monoblockbase',
            options={'ordering': ['motherboard_type', 'ram_type', 'name'], 'verbose_name': 'AIO', 'verbose_name_plural': 'AIOs'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['ram_type', 'capacity_gb', 'name'], 'verbose_name': 'RAM', 'verbose_name_plural': 'RAMs'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['kind', 'interface', 'capacity_gb', 'name'], 'verbose_name': 'Storage', 'verbose_name_plural': 'Storages'},
        ),
        migrations.AlterField(
            model_name='monoblockbase',
            name='motherboard_type',
            field=models.CharField(max_length=10),
        ),
    ]
