# Generated by Django 6.0.5 on 2026-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_keyboardmouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monoblockbase',
            name='motherboard_type',
            field=models.CharField(max_length=10, verbose_name='MB Type'),
        ),
    ]
