# Generated by Django 5.2.14 on 2026-05-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_replace_sata_ports_with_supports_sata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'ordering': ['price', 'name'], 'verbose_name': 'CPU', 'verbose_name_plural': 'CPUs'},
        ),
        migrations.AlterModelOptions(
            name='keyboardmouse',
            options={'ordering': ['price', 'name'], 'verbose_name': 'Keyboard and Mouse', 'verbose_name_plural': 'Keyboard and Mouse'},
        ),
        migrations.AlterModelOptions(
            name='monoblockbase',
            options={'ordering': ['price', 'name'], 'verbose_name': 'AIO', 'verbose_name_plural': 'AIOs'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['price', 'name'], 'verbose_name': 'RAM', 'verbose_name_plural': 'RAMs'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['price', 'name'], 'verbose_name': 'Storage', 'verbose_name_plural': 'Storages'},
        ),
    ]
